# Generated by Django 3.1.4 on 2020-12-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notified_flag',
            field=models.BooleanField(default=False),
        ),
    ]
